/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.40                          *
*        Compiled Jun 22 2017, 10:13:26                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0      (GUI_ID_USER + 0x00)
#define ID_TEXT_0      (GUI_ID_USER + 0x01)
#define ID_TEXT_1      (GUI_ID_USER + 0x02)
#define ID_GRAPH_0      (GUI_ID_USER + 0x03)
#define ID_TEXT_2      (GUI_ID_USER + 0x04)
#define ID_BUTTON_0      (GUI_ID_USER + 0x05)
#define ID_CHECKBOX_0      (GUI_ID_USER + 0x06)
#define ID_CHECKBOX_1      (GUI_ID_USER + 0x07)
#define ID_BUTTON_1      (GUI_ID_USER + 0x08)
#define ID_BUTTON_2      (GUI_ID_USER + 0x09)
#define ID_BUTTON_3      (GUI_ID_USER + 0x0A)
#define ID_BUTTON_4      (GUI_ID_USER + 0x0B)
#define ID_TEXT_3      (GUI_ID_USER + 0x0C)
#define ID_TEXT_4      (GUI_ID_USER + 0x0D)


// USER START (Optionally insert additional defines)
WM_HWIN hTimeStr;
WM_HWIN hAdcStr;
WM_HWIN hTempStr;
WM_HWIN hGraph;
GRAPH_DATA_Handle hData;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Projeto_1", ID_FRAMEWIN_0, 0, 0, 320, 240, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "TimeStr", ID_TEXT_0, 25, 35, 147, 31, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Clock_Label", ID_TEXT_1, 25, 15, 129, 20, 0, 0x64, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 12, 105, 200, 100, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Analog_Label", ID_TEXT_2, 16, 86, 196, 20, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Adjust", ID_BUTTON_0, 195, 42, 80, 25, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "ADC_Checkbox", ID_CHECKBOX_0, 226, 118, 80, 21, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Temp_Checkbox", ID_CHECKBOX_1, 226, 159, 80, 22, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "OK", ID_BUTTON_1, 240, 20, 50, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Up", ID_BUTTON_2, 183, 21, 50, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Down", ID_BUTTON_3, 183, 64, 50, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Next", ID_BUTTON_4, 240, 64, 50, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "AdcStr", ID_TEXT_3, 250, 142, 50, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 250, 183, 51, 20, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Projeto_1'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetTitleHeight(hItem, 20);
    //
    // Initialization of 'TimeStr'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "00:00:00.0");
    TEXT_SetFont(hItem, GUI_FONT_32B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_TOP);
    //
    // Initialization of 'Clock_Label'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "Clock");
    //
    // Initialization of 'Analog_Label'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetText(hItem, "Analog");
    //
    // Initialization of 'Adjust'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "Adjust");
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'ADC_Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetText(hItem, "ADC");
    //
    // Initialization of 'Temp_Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
    CHECKBOX_SetText(hItem, "Temp");
    //
    // Initialization of 'OK'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'AdcStr'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000000FF));
    TEXT_SetText(hItem, "0000");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF0000));
    TEXT_SetText(hItem, "00ºC");
    // USER START (Optionally insert additional code for further widget initialization)

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_20_1);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_20_1);

    //
    // Initialization of 'ADC_Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetSkinClassic(hItem);
    //
    // Initialization of 'Temp_Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
    CHECKBOX_SetSkinClassic(hItem);

    /*
     *  Dialog Init
     */
    hItem = pMsg->hWin;
    FRAMEWIN_SetSkinClassic(hItem);
    FRAMEWIN_SetBarColor(hItem, 0, GUI_GRAY);
    FRAMEWIN_SetClientColor(hItem, GUI_GRAY_E7);
    /*
     * Buttons init
     */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
//  BUTTON_SetSkinClassic(hItem);
	WM_HideWindow(hItem); /* Button_Next */
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
//	BUTTON_SetSkinClassic(hItem);
	WM_HideWindow(hItem); /* Button_OK */
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
//	BUTTON_SetSkinClassic(hItem);
	WM_HideWindow(hItem); /* Button_Up */
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
//	BUTTON_SetSkinClassic(hItem);
	WM_HideWindow(hItem); /* Button_Down */
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
//	BUTTON_SetSkinClassic(hItem);
	WM_ShowWindow(hItem); /* Button_Adjust */
	/*
	 * Graph init
	 */
//	GRAPH_SCALE_Handle hScale;
//	WM_HWIN hGraph = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);;
//	hData = GRAPH_DATA_YT_Create(GUI_DARKGREEN, 100, Data, 1000);
//	GRAPH_AttachData(hGraph, hData);
//	hScale = GRAPH_SCALE_Create(28, GUI_TA_RIGHT, GRAPH_SCALE_CF_VERTICAL, 20);
//	GRAPH_AttachScale(hGraph, hScale);
	/*
	 * Passing global handlers
	 */
	hTimeStr = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	hAdcStr = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
	hTempStr = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Adjust'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
    	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    	WM_ShowWindow(hItem); /* Button_Next */
    	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    	WM_ShowWindow(hItem); /* Button_OK */
      	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
      	WM_ShowWindow(hItem); /* Button_Up */
      	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
      	WM_ShowWindow(hItem); /* Button_Down */
      	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
      	WM_HideWindow(hItem); /* Button_Adjust */
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_0: // Notifications sent by 'ADC_Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_1: // Notifications sent by 'Temp_Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'OK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
    	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    	WM_HideWindow(hItem); /* Button_Next */
    	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
      	WM_HideWindow(hItem); /* Button_OK */
      	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
      	WM_HideWindow(hItem); /* Button_Up */
      	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
      	WM_HideWindow(hItem); /* Button_Down */
      	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
      	WM_ShowWindow(hItem); /* Button_Adjust */
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Up'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Down'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Next'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateProjeto_1
*/
WM_HWIN CreateProjeto_1(void);
WM_HWIN CreateProjeto_1(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
