/**
 *  @file SYS.c
 *
 *  System Control driver wrapper for
 *  STM32F429ZI Nucleo board platform.
 *  Limited configuration capability.
 *
 *  Created on: 12 de nov de 2017
 *  Author: Gilberto Araujo
 */

#include "stm32f4xx_hal.h"
#include "SYS.h"

/*
 * Private definitions
 */

/* PWREx Regulator Voltage Scale */
static const uint32_t VoltageScaleMode[] =
{
	PWR_REGULATOR_VOLTAGE_SCALE3,	/* Scale 3 Mode: the maximum value of fHCLK is 120 MHz. */
	PWR_REGULATOR_VOLTAGE_SCALE3,
	PWR_REGULATOR_VOLTAGE_SCALE3,
	PWR_REGULATOR_VOLTAGE_SCALE3,
	PWR_REGULATOR_VOLTAGE_SCALE3,
	PWR_REGULATOR_VOLTAGE_SCALE3,
	PWR_REGULATOR_VOLTAGE_SCALE3,
	PWR_REGULATOR_VOLTAGE_SCALE3,
	PWR_REGULATOR_VOLTAGE_SCALE3,
	PWR_REGULATOR_VOLTAGE_SCALE1,	/* Scale 1 Mode(default value at reset): the maximum value of fHCLK is 168 MHz. */
	PWR_REGULATOR_VOLTAGE_SCALE1,   /* It can be extended to 180 MHz by activating the over-drive mode. */
	PWR_REGULATOR_VOLTAGE_SCALE1,
	PWR_REGULATOR_VOLTAGE_SCALE1,
	PWR_REGULATOR_VOLTAGE_SCALE1,
	PWR_REGULATOR_VOLTAGE_SCALE1
};

static const uint32_t OscInitTable[][6] =
{/* {OscType, HSEState, HSIState, HSICalibrationValue, LSEState, LSIState} */
	{RCC_OSCILLATORTYPE_HSI | RCC_OSCILLATORTYPE_LSE | RCC_OSCILLATORTYPE_LSI,
	 RCC_HSE_OFF, RCC_HSI_ON, RCC_HSICALIBRATION_DEFAULT, RCC_LSE_ON, RCC_LSI_ON},
	{RCC_OSCILLATORTYPE_HSE | RCC_OSCILLATORTYPE_LSE | RCC_OSCILLATORTYPE_LSI,
	 RCC_HSE_BYPASS, RCC_HSI_OFF, RCC_HSICALIBRATION_DEFAULT, RCC_LSE_ON, RCC_LSI_ON},
	{RCC_OSCILLATORTYPE_HSE | RCC_OSCILLATORTYPE_LSE | RCC_OSCILLATORTYPE_LSI,
	 RCC_HSE_ON, RCC_HSI_OFF, RCC_HSICALIBRATION_DEFAULT, RCC_LSE_ON, RCC_LSI_ON},

	{RCC_OSCILLATORTYPE_HSI | RCC_OSCILLATORTYPE_LSE | RCC_OSCILLATORTYPE_LSI,
	 RCC_HSE_OFF, RCC_HSI_ON, RCC_HSICALIBRATION_DEFAULT, RCC_LSE_ON, RCC_LSI_ON},
	{RCC_OSCILLATORTYPE_HSE | RCC_OSCILLATORTYPE_LSE | RCC_OSCILLATORTYPE_LSI,
	 RCC_HSE_BYPASS, RCC_HSI_OFF, RCC_HSICALIBRATION_DEFAULT, RCC_LSE_ON, RCC_LSI_ON},
	{RCC_OSCILLATORTYPE_HSE | RCC_OSCILLATORTYPE_LSE | RCC_OSCILLATORTYPE_LSI,
	 RCC_HSE_ON, RCC_HSI_OFF, RCC_HSICALIBRATION_DEFAULT, RCC_LSE_ON, RCC_LSI_ON},

	{RCC_OSCILLATORTYPE_HSI | RCC_OSCILLATORTYPE_LSE | RCC_OSCILLATORTYPE_LSI,
	 RCC_HSE_OFF, RCC_HSI_ON, RCC_HSICALIBRATION_DEFAULT, RCC_LSE_ON, RCC_LSI_ON},
	{RCC_OSCILLATORTYPE_HSE | RCC_OSCILLATORTYPE_LSE | RCC_OSCILLATORTYPE_LSI,
	 RCC_HSE_BYPASS, RCC_HSI_OFF, RCC_HSICALIBRATION_DEFAULT, RCC_LSE_ON, RCC_LSI_ON},
	{RCC_OSCILLATORTYPE_HSE | RCC_OSCILLATORTYPE_LSE | RCC_OSCILLATORTYPE_LSI,
	 RCC_HSE_ON, RCC_HSI_OFF, RCC_HSICALIBRATION_DEFAULT, RCC_LSE_ON, RCC_LSI_ON},

	{RCC_OSCILLATORTYPE_HSI | RCC_OSCILLATORTYPE_LSE | RCC_OSCILLATORTYPE_LSI,
	 RCC_HSE_OFF, RCC_HSI_ON, RCC_HSICALIBRATION_DEFAULT, RCC_LSE_ON, RCC_LSI_ON},
	{RCC_OSCILLATORTYPE_HSE | RCC_OSCILLATORTYPE_LSE | RCC_OSCILLATORTYPE_LSI,
	 RCC_HSE_BYPASS, RCC_HSI_OFF, RCC_HSICALIBRATION_DEFAULT, RCC_LSE_ON, RCC_LSI_ON},
	{RCC_OSCILLATORTYPE_HSE | RCC_OSCILLATORTYPE_LSE | RCC_OSCILLATORTYPE_LSI,
	 RCC_HSE_ON, RCC_HSI_OFF, RCC_HSICALIBRATION_DEFAULT, RCC_LSE_ON, RCC_LSI_ON},

	{RCC_OSCILLATORTYPE_HSI | RCC_OSCILLATORTYPE_LSE | RCC_OSCILLATORTYPE_LSI,
	 RCC_HSE_OFF, RCC_HSI_ON, RCC_HSICALIBRATION_DEFAULT, RCC_LSE_ON, RCC_LSI_ON},
	{RCC_OSCILLATORTYPE_HSE | RCC_OSCILLATORTYPE_LSE | RCC_OSCILLATORTYPE_LSI,
	 RCC_HSE_BYPASS, RCC_HSI_OFF, RCC_HSICALIBRATION_DEFAULT, RCC_LSE_ON, RCC_LSI_ON},
	{RCC_OSCILLATORTYPE_HSE | RCC_OSCILLATORTYPE_LSE | RCC_OSCILLATORTYPE_LSI,
	 RCC_HSE_ON, RCC_HSI_OFF, RCC_HSICALIBRATION_DEFAULT, RCC_LSE_ON, RCC_LSI_ON},
};

static const uint32_t OscPLLInitTable[][6] =
{/* {PLLSource, PLLState, PLLM, PLLN, PLLP, PLLQ} */
	{RCC_PLLSOURCE_HSI, RCC_PLL_OFF, 4, 96, RCC_PLLP_DIV6, 4},
	{RCC_PLLSOURCE_HSE, RCC_PLL_ON, 4, 96, RCC_PLLP_DIV6, 4},
	{RCC_PLLSOURCE_HSE, RCC_PLL_ON, 4, 96, RCC_PLLP_DIV6, 4},

	{RCC_PLLSOURCE_HSI, RCC_PLL_ON, 8, 72, RCC_PLLP_DIV2, 3},
	{RCC_PLLSOURCE_HSE, RCC_PLL_ON, 4, 72, RCC_PLLP_DIV2, 3},
	{RCC_PLLSOURCE_HSE, RCC_PLL_ON, 4, 72, RCC_PLLP_DIV2, 3},

	{RCC_PLLSOURCE_HSI, RCC_PLL_ON, 8, 120, RCC_PLLP_DIV2, 5},
	{RCC_PLLSOURCE_HSE, RCC_PLL_ON, 4, 120, RCC_PLLP_DIV2, 5},
	{RCC_PLLSOURCE_HSE, RCC_PLL_ON, 4, 120, RCC_PLLP_DIV2, 5},

	{RCC_PLLSOURCE_HSI, RCC_PLL_ON, 8, 168, RCC_PLLP_DIV2, 7},
	{RCC_PLLSOURCE_HSE, RCC_PLL_ON, 4, 168, RCC_PLLP_DIV2, 7},
	{RCC_PLLSOURCE_HSE, RCC_PLL_ON, 4, 168, RCC_PLLP_DIV2, 7},

	{RCC_PLLSOURCE_HSI, RCC_PLL_ON, 8, 180, RCC_PLLP_DIV2, 7},
	{RCC_PLLSOURCE_HSE, RCC_PLL_ON, 4, 180, RCC_PLLP_DIV2, 7},
	{RCC_PLLSOURCE_HSE, RCC_PLL_ON, 4, 180, RCC_PLLP_DIV2, 7}
};

static const uint32_t ClockInitTable[][5] =
{/* {ClockType, SYSCLKSource, AHBCLKDivider, APB1CLKDivider, APB2CLKDivider} */
	{RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2,
	 RCC_SYSCLKSOURCE_HSI, RCC_SYSCLK_DIV1, RCC_HCLK_DIV4, RCC_HCLK_DIV2},
	{RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2,
	 RCC_SYSCLKSOURCE_PLLCLK, RCC_SYSCLK_DIV2, RCC_HCLK_DIV4, RCC_HCLK_DIV2},
	{RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2,
	 RCC_SYSCLKSOURCE_PLLCLK, RCC_SYSCLK_DIV2, RCC_HCLK_DIV4, RCC_HCLK_DIV2},

	{RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2,
	 RCC_SYSCLKSOURCE_PLLCLK, RCC_SYSCLK_DIV1, RCC_HCLK_DIV2, RCC_HCLK_DIV1},
	{RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2,
	 RCC_SYSCLKSOURCE_PLLCLK, RCC_SYSCLK_DIV1, RCC_HCLK_DIV2, RCC_HCLK_DIV1},
	{RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2,
	 RCC_SYSCLKSOURCE_PLLCLK, RCC_SYSCLK_DIV1, RCC_HCLK_DIV2, RCC_HCLK_DIV1},

	{RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2,
	 RCC_SYSCLKSOURCE_PLLCLK, RCC_SYSCLK_DIV1, RCC_HCLK_DIV4, RCC_HCLK_DIV2},
	{RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2,
	 RCC_SYSCLKSOURCE_PLLCLK, RCC_SYSCLK_DIV1, RCC_HCLK_DIV4, RCC_HCLK_DIV2},
	{RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2,
	 RCC_SYSCLKSOURCE_PLLCLK, RCC_SYSCLK_DIV1, RCC_HCLK_DIV4, RCC_HCLK_DIV2},

	{RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2,
	 RCC_SYSCLKSOURCE_PLLCLK, RCC_SYSCLK_DIV1, RCC_HCLK_DIV4, RCC_HCLK_DIV2},
	{RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2,
	 RCC_SYSCLKSOURCE_PLLCLK, RCC_SYSCLK_DIV1, RCC_HCLK_DIV4, RCC_HCLK_DIV2},
	{RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2,
	 RCC_SYSCLKSOURCE_PLLCLK, RCC_SYSCLK_DIV1, RCC_HCLK_DIV4, RCC_HCLK_DIV2},

	{RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2,
	 RCC_SYSCLKSOURCE_PLLCLK, RCC_SYSCLK_DIV1, RCC_HCLK_DIV4, RCC_HCLK_DIV2},
	{RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2,
	 RCC_SYSCLKSOURCE_PLLCLK, RCC_SYSCLK_DIV1, RCC_HCLK_DIV4, RCC_HCLK_DIV2},
	{RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2,
	 RCC_SYSCLKSOURCE_PLLCLK, RCC_SYSCLK_DIV1, RCC_HCLK_DIV4, RCC_HCLK_DIV2},
};

static const uint32_t FLASHLatency[] =
{
	FLASH_LATENCY_0, FLASH_LATENCY_0, FLASH_LATENCY_0,
	FLASH_LATENCY_2, FLASH_LATENCY_2, FLASH_LATENCY_2,
	FLASH_LATENCY_3, FLASH_LATENCY_3, FLASH_LATENCY_3,
	FLASH_LATENCY_5, FLASH_LATENCY_5, FLASH_LATENCY_5,
	FLASH_LATENCY_5, FLASH_LATENCY_5, FLASH_LATENCY_5
};

/*
 * Private prototypes
 */
static void SYS_Error_Handler(char * file, int line);

/**
 * System initialization.
 * Reset of all peripherals, initializes the Flash interface and the Systick.
 */
void SYS_Init(void)
{
	/* Initializes the Hardware Abstraction Layer (HAL) */
	HAL_Init();
}
/**
 * Set system clock.
 * Configures the Oscillator, Clock and Peripheral init structures.
 * @param sysClock Clock configuration Id.
 */
void SYS_ClockSet(sysClk_t sysClock)
{
	RCC_OscInitTypeDef RCC_OscInitStruct;
	RCC_ClkInitTypeDef RCC_ClkInitStruct;
	RCC_PeriphCLKInitTypeDef PeriphClkInitStruct;

	/* Configure the main internal regulator output voltage */
	__HAL_RCC_PWR_CLK_ENABLE();
	__HAL_PWR_VOLTAGESCALING_CONFIG( VoltageScaleMode[sysClock] );

	/* Initializes Oscillators and PLL */
	RCC_OscInitStruct.OscillatorType = OscInitTable[sysClock][0];
	RCC_OscInitStruct.HSEState = OscInitTable[sysClock][1];
	RCC_OscInitStruct.HSIState = OscInitTable[sysClock][2];
	RCC_OscInitStruct.HSICalibrationValue = OscInitTable[sysClock][3];
	RCC_OscInitStruct.LSEState = OscInitTable[sysClock][4];
	RCC_OscInitStruct.LSIState = OscInitTable[sysClock][5];
	RCC_OscInitStruct.PLL.PLLSource = OscPLLInitTable[sysClock][0];
	RCC_OscInitStruct.PLL.PLLState = OscPLLInitTable[sysClock][1];
	RCC_OscInitStruct.PLL.PLLM = OscPLLInitTable[sysClock][2];
	RCC_OscInitStruct.PLL.PLLN = OscPLLInitTable[sysClock][3];
	RCC_OscInitStruct.PLL.PLLP = OscPLLInitTable[sysClock][4];
	RCC_OscInitStruct.PLL.PLLQ = OscPLLInitTable[sysClock][5];

	if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
	{
		SYS_Error_Handler(__FILE__, __LINE__);
	}

	/* Activate the Over-Drive mode (for clocks higher than 168 MHz) */
	if (sysClock > SYS_CLOCK_168_MHZ_XTAL)
	{
		if (HAL_PWREx_EnableOverDrive() != HAL_OK)
		{
			SYS_Error_Handler(__FILE__, __LINE__);
		}
	}
	/* Initializes the CPU, AHB and APB busses clocks */
	RCC_ClkInitStruct.ClockType = ClockInitTable[sysClock][0];
	RCC_ClkInitStruct.SYSCLKSource = ClockInitTable[sysClock][1];
	RCC_ClkInitStruct.AHBCLKDivider = ClockInitTable[sysClock][2];
	RCC_ClkInitStruct.APB1CLKDivider = ClockInitTable[sysClock][3];
	RCC_ClkInitStruct.APB2CLKDivider = ClockInitTable[sysClock][4];

  	if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASHLatency[sysClock]) != HAL_OK)
	{
  		SYS_Error_Handler(__FILE__, __LINE__);
	}

	/* Initializes the RTC Peripheral clock */
	PeriphClkInitStruct.PeriphClockSelection = RCC_PERIPHCLK_RTC;
	PeriphClkInitStruct.RTCClockSelection = RCC_RTCCLKSOURCE_LSE;
	if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInitStruct) != HAL_OK)
	{
		SYS_Error_Handler(__FILE__, __LINE__);
	}

  	/* Configures the Systick */
	HAL_SYSTICK_Config(HAL_RCC_GetHCLKFreq()/1000);
	HAL_SYSTICK_CLKSourceConfig(SYSTICK_CLKSOURCE_HCLK);
	HAL_NVIC_SetPriority(SysTick_IRQn, 15, 0);
}
/**
 * Get system clock (in Hz)
 */
uint32_t SYS_ClockGet()
{
	return HAL_RCC_GetSysClockFreq();
}
/**
 * Set system power mode
 * @param mode Mode configuration Id.
 */
void SYS_PowerModeSet(sysMode_t mode)
{
	switch (mode)
	{
		case SYS_PWR_MODE_SLEEP:
			HAL_PWR_EnterSLEEPMode(PWR_MAINREGULATOR_ON, PWR_SLEEPENTRY_WFI);
			break;
		case SYS_PWR_MODE_DEEPSLEEP:
			HAL_PWR_EnterSTANDBYMode();
			break;
		default:
			break;
	}
}
/**
 * This function is executed when an error occurs.
 * @param file File in which error occurs.
 * @param line Line in which error occurs.
 */
static
void SYS_Error_Handler(char * file, int line)
{
  while(1)
  {
  }
}

